Models/Computer.cs
namespace MvcLabManager.Models;

public class Computer
{
    public int Id { get; set; }
    public string Ram { get; set; }
    public string Processor { get; set; }

    public Computer() { }

    public Computer(int id, string ram, string processor)
    {
        Id = id;
        Ram = ram;
        Processor = processor;
    }
}

Models/ErrorViewModel.cs
namespace MvcLabManager.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/LabManagerContext.cs
using Microsoft.EntityFrameworkCore;

namespace MvcLabManager.Models;

public class LabManagerContext : DbContext
{
    public DbSet<Computer> Computers { get; set; }
    
    public DbSet<Laboratory> Laboratories { get; set; }
    
    public LabManagerContext(DbContextOptions<LabManagerContext> options) : base(options)
    {
        
    }
}

Models/Laboratory.cs
namespace MvcLabManager.Models;

public class Laboratory
{
    public int Id { get; set; }
    public int Number { get; set; }
    public string Name { get; set; }
    public string Block { get; set; }

    public Laboratory() { }

    public Laboratory(int id, int number, string name, string block)
    {
        Id = id;
        Number = number;
        Name = name;
        Block = block;
    }
}

Controllers/ComputerController.cs
using Microsoft.AspNetCore.Mvc;
using MvcLabManager.Models;

namespace MvcLabManager.Controllers;

public class ComputerController : Controller
{
    private readonly LabManagerContext _context;

    public ComputerController(LabManagerContext context)
    {
        _context = context;
    }

    public IActionResult Index()
    {

        return View(_context.Computers);
    }

    public IActionResult Show(int id)
    {
        Computer? computer =_context.Computers.Find(id);

        if(computer == null)
        {
            return NotFound();
        }
        return View(computer);
    }

    public IActionResult Create()
    {      
        return View();
    }

    public IActionResult CreateResult(int id, string ram, string processor)
    {
        if(_context.Computers.Find(id) == null)
        {
            _context.Computers.Add(new Computer(id, ram, processor));
            _context.SaveChanges();
            return RedirectToAction("Create");
        }
        else
        {
           return Content("Já existe um computador com esse id.");
        }
       
    }

    public IActionResult Delete(int id)
    {
        _context.Computers.Remove(_context.Computers.Find(id));
        _context.SaveChanges();
        return View();
    }

    public IActionResult Update(int id)
    {
        Computer computer = _context.Computers.Find(id);
        if(computer == null)
        {
            return Content("Esse computador não existe.");
        }
        else
        {
           return View(computer);
        }
    }

    public IActionResult UpdateResult(int id, string ram, string processor)
    {
        Computer computer = _context.Computers.Find(id);

        computer.Ram = ram;
        computer.Processor = processor;
        _context.SaveChanges();
        return RedirectToAction("Index");
    }   
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MvcLabManager.Models;

namespace MvcLabManager.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/LaboratoryController.cs
using Microsoft.AspNetCore.Mvc;
using MvcLabManager.Models;

namespace MvcLabManager.Controllers;

public class LaboratoryController : Controller
{
    private readonly LabManagerContext _context;

    public LaboratoryController(LabManagerContext context)
    {
        _context = context;
    }

    public IActionResult Index()
    {

        return View(_context.Laboratories);
    }

    public IActionResult Show(int id)
    {
        Laboratory? laboratory =_context.Laboratories.Find(id);

        if(laboratory == null)
        {
            return NotFound();
        }
        return View(laboratory);
    }

    public IActionResult Create(){
                
        return View();
    }

    public IActionResult Creation(int id, int number, string name, string block){
        if(_context.Laboratories.Find(id) == null)
        {
            _context.Laboratories.Add(new Laboratory(id,number,name,block));
            _context.SaveChanges();
            return RedirectToAction("Create");
        }
        else
        {
           return Content("Já existe um laboratorio com esse id");
        }
       
    }

    public IActionResult Delete(int id){
        _context.Laboratories.Remove(_context.Laboratories.Find(id));
        _context.SaveChanges();
        return View();
    }

    public IActionResult Update(int id){
        Laboratory laboratory = _context.Laboratories.Find(id);
        if(laboratory == null)
        {
            return Content("Esse laboratorio não existe!");
        }
        else
        {
           return View(laboratory);
        }
    }

    public IActionResult Updation(int id, int number, string name, string block){
        Laboratory laboratory = _context.Laboratories.Find(id);

        laboratory.Number = number;
        laboratory.Name = name;
        laboratory.Block = block;
        _context.SaveChanges();
        return RedirectToAction("Index");
    }
    
}

Views/Computer/Create.cshtml
@{
    ViewData["Title"] = "Criar computadores";
}

<div class="text">
    <h1 >Cadastrar um novo computador</h1>
    <hr>
</div>


<form action="CreateResult" method="post">
    <table>
        <tr>
            <td>Id:</td>
            <td><input type="text" name="id" id="id" class="form-control" required></td>
        </tr>

        <tr>
            <td>Ram:</td>
            <td><input type="text" name="ram" id="ram" class="form-control" required></td>
        </tr>

        <tr>
            <td>Processador:</td>
            <td><input type="text" name="processor" id="processor" class="form-control" required></td>
        </tr>

        <tr>
            <td> <button type="submit" class="btn btn-primary">Enviar</button></td>
        </tr>

    </table>
</form>

Views/Computer/Delete.cshtml
@{
    ViewData["Title"] = "Error";
    var nome = ViewData["nome"];
}

<h1>Computador deletado com sucesso.</h1>
 <a href="/Computer/Index"><button type="submit" class="btn btn-primary">Voltar a Lista</button></a>

Views/Computer/Index.cshtml
@model IEnumerable<MvcLabManager.Models.Computer>

@{
    ViewData["Title"] = "Computadores";
}
<h1>@ViewData["Title"]</h1>

@if (Model.Count() == 0)
{
    <p>Nenhum computador cadastrado.</p>    
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Ram</th>
                <th>Processador</th>
                <th></th>
            </tr>
            <tbody>
                @foreach(var computer in Model)
                {
                    <tr>
                        <td>@computer.Id</td>
                        <td>@computer.Ram</td>
                        <td>@computer.Processor</td>
                        <td>
                            <a href="/Computer/Show/@computer.Id">Ver</a>
                        </td>
                    </tr>
                }
            </tbody>
        </thead>
    </table>
}

Views/Computer/Show.cshtml
@model MvcLabManager.Models.Computer

@{
    //interpolação de string (colocar uma prop dentro de uma string - não precisa concatenar)
    ViewData["Title"] = $"Computador {Model.Id}";
}
<h1>@ViewData["Title"]</h1>

<p><b>Id:</b> @Model.Id</p>
<p><b>Ram:</b> @Model.Ram</p>
<p><b>Processor:</b> @Model.Processor</p>

 <a href="/Computer/Show/@Model.Id">
    <button type="button">Detalhes</button>
</a>

<a href="/Computer/Delete/@Model.Id">
    <button type="button">Deletar</button>
</a>

<a href="/Computer/Update/@Model.Id">
    <button type="button">Atualizar</button>
</a>

Views/Computer/Update.cshtml
@{
    ViewData["Title"] = "Atualizar um computador";
}

<div class="text">
    <h1>Atualizar as informações de um computador:</h1>
    <hr>
</div>


<form action="../UpdateResult" method="post">
    <table>
        <tr>
            <td>Digite o Id:</td>
            <td><input type="text" name="id" id="id" class="form-control" required></td>
        </tr>

        <tr>
            <td>Ram:</td>
            <td><input type="text" name="ram" id="ram" class="form-control" required></td>
        </tr>

        <tr>
            <td>Processador:</td>
            <td><input type="text" name="processor" id="processor" class="form-control" required></td>
        </tr>

        <tr>
            <td> <button type="submit" class="btn btn-primary">Enviar</button></td>
        </tr>

    </table>
</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Laboratory/Create.cshtml
@{
    ViewData["Title"] = "Criar laboratórios";
}

<div class="text">
    <h1>Cadastrar um novo laboratório</h1>
    <hr>
</div>

<form action="CreateResult" method="post">
    <table>
        <tr>
            <td>Id:</td>
            <td><input type="text" name="id" id="id" class="form-control" required></td>
        </tr>

        <tr>
            <td>Número:</td>
            <td><input type="text" name="number" id="number" class="form-control" required></td>
        </tr>

        <tr>
            <td>Nome:</td>
            <td><input type="text" name="name" id="name" class="form-control" required></td>
        </tr>

        <tr>
            <td>Bloco:</td>
            <td><input type="text" name="block" id="block" class="form-control" required></td>
        </tr>

        <tr>
            <td> <button type="submit" class="btn btn-primary">Enviar</button></td>
        </tr>

    </table>
</form>

Views/Laboratory/CreateResult.cshtml
@{
    ViewData["Title"] = "Error";
    var nome = ViewData["nome"];
}

Views/Laboratory/Delete.cshtml
@{
    ViewData["Title"] = "Error";
    var nome = ViewData["nome"];
}

<h1>Laboratório deletado com sucesso.</h1>
 <a href="/Laboratory/Index"><button type="submit" class="btn btn-primary">Voltar a Lista</button></a>

Views/Laboratory/Index.cshtml
@model IEnumerable<MvcLabManager.Models.Laboratory>

@{
    ViewData["Title"] = "Laboratórios";
}
<h1>@ViewData["Title"]</h1>

@if (Model.Count() == 0)
{
    <p>Nenhum laboratório cadastrado.</p>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>Id</th> 
                <th>Número</th> 
                <th>Nome</th> 
                <th>Bloco</th>
                <th></th>
            </tr>

            <tbody>
                @foreach(var laboratory in Model)
                {
                    <tr>
                        <td>@laboratory.Id</td> 
                        <td>@laboratory.Number</td> 
                        <td>@laboratory.Name</td> 
                        <td>@laboratory.Block</td> 
                        <th>
                            <a href="/Laboratory/Show/@laboratory.Id">Ver</a>
                        </th>
                    </tr>
                }
            </tbody>

        </thead>
    </table>
}

Views/Laboratory/Show.cshtml
@model MvcLabManager.Models.Laboratory;

@{
    ViewData["Title"] = $"Laboratório:  {Model.Id}";
}
<h1>@ViewData["Title"]</h1>

<p><b>Id: </b> @Model.Id</p>
<p><b>Número: </b> @Model.Number</p>
<p><b>Nome: </b> @Model.Name</p>
<p><b>Bloco: </b> @Model.Block</p>

<a href="/Laboratory/Show/@Model.Id">
    <button type="button">Detalhes</button>
</a>
<a href="/Laboratory/Delete/@Model.Id">
    <button type="button">Deletar</button>
</a>
<a href="/Laboratory/Update/@Model.Id">
    <button type="button">Atualizar</button>
</a>

Views/Laboratory/Update.cshtml
@{
    ViewData["Title"] = "Atualizar Laboratorio";
}

<div class="text">
    <h1>Atualizar as informações do laboratório:</h1>
    <hr>
</div>


<form action="../UpdateResult" method="post">
    <table>
        <tr>
            <td>Informe o Id:</td>
            <td><input type="text" name="id" id="id" class="form-control" required></td>
        </tr>

        <tr>
            <td>Número:</td>
            <td><input type="text" name="number" id="number" class="form-control" required></td>
        </tr>

        <tr>
            <td>Nome:</td>
            <td><input type="text" name="name" id="name" class="form-control" required></td>
        </tr>

        <tr>
            <td>Bloco:</td>
            <td><input type="text" name="block" id="block" class="form-control" required></td>
        </tr>

        <tr>
            <td> <button type="submit" class="btn btn-primary">Enviar</button></td>
        </tr>

    </table>
</form>

Views/Laboratory/UpdateResult.cshtml
@{
    ViewData["Title"] = "Error";
    var nome = ViewData["nome"];
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcLabManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcLabManager.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcLabManager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Computer" asp-action="Index">Listar comps</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Computer" asp-action="Create">Criar comps</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Laboratory" asp-action="Index">Listar labs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Laboratory" asp-action="Create">Criar labs</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MvcLabManager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>